import type { Film, AcademyProgram, Article, DSHEvent } from "./types";

/* ═══════════════════════════════════════
   Mock data — swap with API calls later
   ═══════════════════════════════════════ */

export const MOCK_FILMS: Film[] = [
  {
    id: "film-001",
    title: "Free Fish",
    slug: "free-fish",
    logline: "A short documentary capturing daily life and resilience in Gaza through the eyes of a young journalist.",
    synopsisShort:
      "Free Fish follows the rhythms of life in Gaza, where fishing boats set out each morning despite blockade restrictions. Through intimate footage, journalist Bisan Owda reveals how ordinary acts become quiet forms of resistance.",
    synopsisLong:
      "Free Fish is a short documentary directed by Bisan Owda that immerses viewers in the daily realities of life under siege in Gaza. The film follows fishermen who navigate increasingly restricted waters, capturing how the simple act of casting a net carries both economic necessity and symbolic weight. Owda weaves together personal testimony, community voices, and striking visual contrasts between the beauty of the Mediterranean coast and the harshness of occupation. The result is a deeply human portrait of a community that refuses to be defined by its confinement, finding freedom in the routines that sustain both body and spirit.",
    editorialContext:
      "Free Fish enters a global conversation about the erasure of Palestinian daily life from mainstream media. At a moment when coverage focuses overwhelmingly on conflict events, this film insists on showing the texture of everyday existence.",
    credits: {
      direction: "Bisan Owda",
      production: "We Are Not Numbers",
      coProduction: "",
      year: "2024",
      duration: "22 min",
      form: "documentary",
      format: "short",
      language: "Arabic",
      country: "Palestine",
    },
    stage: "festivals",
    themes: ["Palestine", "Resistance", "Daily Life", "Journalism", "Siege"],
    trailerUrl: "https://vimeo.com/example/freefish",
    thumbnailUrl: "/images/slider2.jpg",
    posterUrl: "/images/slider2.jpg",
    festivals: [
      { name: "Sheffield DocFest", year: "2024", selection: "Official Selection" },
      { name: "Carthage Film Festival", year: "2024", award: "Best Short Documentary" },
    ],
    pressQuotes: [
      { source: "Screen Daily", quote: "A devastatingly tender portrait of life under siege." },
      { source: "Middle East Eye", quote: "Owda captures what headlines cannot: the stubborn normalcy of a people who refuse erasure." },
    ],
    screenings: [
      { event: "Sheffield DocFest 2024", date: "2024-06-14", location: "Sheffield, UK", type: "festival" },
      { event: "Palestine Film Institute Tour", date: "2024-09-20", location: "London, UK", type: "community" },
    ],
    accessMode: "request_only",
    status: "published",
    isFeatured: true,
    createdAt: "2024-05-10T12:00:00Z",
    updatedAt: "2025-03-15T09:30:00Z",
  },
  {
    id: "film-003",
    title: "Beneath the Canopy",
    slug: "beneath-the-canopy",
    logline: "An immersive documentary following indigenous land defenders in the Brazilian Amazon as they confront illegal logging networks.",
    synopsisShort:
      "Beneath the Canopy embeds with Munduruku and Kayapo communities as they organise patrols, document encroachment, and fight for territorial sovereignty.",
    synopsisLong:
      "Beneath the Canopy is a feature documentary that spends eighteen months with indigenous land defenders in the Tapajos River basin of the Brazilian Amazon. The film follows community patrols that monitor illegal logging, captures tense confrontations with armed operators, and documents the political manoeuvring that enables deforestation at industrial scale. By centering indigenous voices and filmmaking practices, the documentary offers an alternative framework for understanding climate action, one rooted in ancestral stewardship rather than technocratic solutions.",
    editorialContext:
      "As global climate discourse increasingly acknowledges indigenous land management as the most effective form of conservation, this film provides the human stories behind the data.",
    credits: {
      direction: "Ana Pataxo & Rafael Lima",
      production: "Terra Firme Films",
      coProduction: "DSH Films",
      year: "2025",
      duration: "108 min",
      form: "documentary",
      format: "feature",
      language: "Munduruku, Portuguese",
      country: "Brazil",
    },
    stage: "distribution",
    themes: ["Climate Justice", "Indigenous Rights", "Amazon", "Land Defense", "Sovereignty"],
    trailerUrl: "https://vimeo.com/example/beneathcanopy",
    thumbnailUrl: "/images/slider1.jpg",
    posterUrl: "/images/slider1.jpg",
    festivals: [
      { name: "IDFA", year: "2025", selection: "Official Competition" },
      { name: "Rio International Film Festival", year: "2025", award: "Audience Award" },
      { name: "Hot Docs", year: "2026", selection: "World Showcase" },
    ],
    pressQuotes: [
      { source: "Variety", quote: "A stunning act of cinematic solidarity with those who guard the lungs of the planet." },
      { source: "The Guardian", quote: "Essential viewing for anyone who claims to care about the climate crisis." },
    ],
    screenings: [
      { event: "IDFA 2025", date: "2025-11-18", location: "Amsterdam, Netherlands", type: "festival" },
      { event: "Greenpeace UK Tour", date: "2026-03-10", location: "Manchester, UK", type: "community" },
      { event: "Cinema Verde Online", date: "2026-05-01", location: "Online", type: "online" },
    ],
    accessMode: "public",
    status: "published",
    isFeatured: true,
    createdAt: "2024-08-15T10:00:00Z",
    updatedAt: "2026-04-20T11:00:00Z",
  },
  {
    id: "film-004",
    title: "Salt and Light",
    slug: "salt-and-light",
    logline: "A fiction short exploring the fractures in a Lebanese family as the economic crisis reshapes their daily reality.",
    synopsisShort:
      "Set over a single weekend in Beirut, Salt and Light follows a family gathering that unravels as the electricity cuts grow longer and the value of their savings evaporates.",
    synopsisLong:
      "Salt and Light is a fiction short film set in contemporary Beirut during the peak of Lebanon's economic collapse. Over the course of a weekend family reunion, three generations gather in a once-grand apartment, now dimmed by rolling blackouts. As the hours pass, long-suppressed tensions surface: a daughter's decision to emigrate, a father's refusal to acknowledge the crisis, a grandmother's quiet acts of preservation.",
    editorialContext:
      "Salt and Light speaks to the lived experience of economic collapse in ways that statistics and news reports cannot.",
    credits: {
      direction: "Nadia Kamal",
      production: "Mashrou3 Films",
      coProduction: "",
      year: "2024",
      duration: "28 min",
      form: "fiction",
      format: "short",
      language: "Arabic, French",
      country: "Lebanon",
    },
    stage: "festivals",
    themes: ["Economic Crisis", "Family", "Lebanon", "Emigration", "Resilience"],
    trailerUrl: "https://vimeo.com/example/saltandlight",
    thumbnailUrl: "/images/journalism.jpg",
    posterUrl: "/images/journalism.jpg",
    festivals: [
      { name: "Cannes Court Metrage", year: "2024", selection: "Official Selection" },
      { name: "Beirut International Film Festival", year: "2024", award: "Best Lebanese Film" },
    ],
    pressQuotes: [
      { source: "Cahiers du Cinema", quote: "A film of extraordinary delicacy, finding the universal in the specifically Lebanese." },
    ],
    screenings: [
      { event: "Cannes Court Metrage 2024", date: "2024-05-20", location: "Cannes, France", type: "festival" },
    ],
    accessMode: "request_only",
    status: "published",
    isFeatured: false,
    createdAt: "2024-03-01T09:00:00Z",
    updatedAt: "2025-01-10T16:00:00Z",
  },
  {
    id: "film-006",
    title: "The Classroom",
    slug: "the-classroom",
    logline: "A short documentary capturing a year inside a makeshift school in northern Syria where education becomes an act of defiance.",
    synopsisShort:
      "In a basement converted into a classroom, a teacher and her students navigate shelling, displacement, and curriculum gaps while insisting on the right to learn.",
    synopsisLong:
      "The Classroom is a short documentary set in Idlib, Syria, following teacher Amina al-Hassan and her class of twenty-three children over an academic year. The film observes the daily rituals of education under bombardment: the morning roll call that reveals who has been displaced overnight, the maths lessons interrupted by airstrikes, the improvised art classes that process trauma into colour.",
    editorialContext:
      "The Classroom contributes to DSH's focus on education as a site of resistance and renewal.",
    credits: {
      direction: "Omar Alshikh",
      production: "Reel Syria Collective",
      coProduction: "DSH Films",
      year: "2024",
      duration: "34 min",
      form: "documentary",
      format: "short",
      language: "Arabic",
      country: "Syria",
    },
    stage: "impact",
    themes: ["Education", "Syria", "Children", "Resistance", "Conflict"],
    trailerUrl: "https://vimeo.com/example/theclassroom",
    thumbnailUrl: "/images/slidere3.jpg",
    posterUrl: "/images/slidere3.jpg",
    festivals: [
      { name: "Sundance", year: "2024", selection: "World Documentary Short" },
      { name: "DOK Leipzig", year: "2024", award: "Golden Dove for Short Film" },
    ],
    pressQuotes: [
      { source: "IndieWire", quote: "A masterclass in observational cinema that trusts its audience completely." },
      { source: "Al Jazeera English", quote: "The most important film about education in conflict zones in a decade." },
    ],
    screenings: [
      { event: "Sundance 2024", date: "2024-01-22", location: "Park City, USA", type: "festival" },
      { event: "UNICEF Education Summit", date: "2024-06-15", location: "Geneva, Switzerland", type: "educational" },
    ],
    accessMode: "public",
    status: "published",
    isFeatured: true,
    createdAt: "2023-11-01T07:00:00Z",
    updatedAt: "2025-06-20T12:00:00Z",
  },
];

export const MOCK_PROGRAMS: AcademyProgram[] = [
  {
    id: "acad-1",
    title: "Documenting Resistance",
    slug: "documenting-resistance",
    type: "course",
    format: "online",
    description: "A filmmaking course for grassroots movements — learn to document struggles for justice with integrity, safety, and cinematic craft.",
    objectives: [
      "Understand ethical documentary practices in conflict zones",
      "Develop narrative structures for grassroots storytelling",
      "Learn field recording techniques with minimal equipment",
      "Build a distribution strategy for impact-driven films",
    ],
    whoLeads: "Rasha Salti",
    whoItsFor: "Activists, community organizers, and aspiring filmmakers working with grassroots movements who want to document resistance with dignity and purpose.",
    duration: "8 weeks",
    isFree: true,
    price: null,
    scholarshipNote: "This program is offered free of charge as part of DSH's commitment to accessible education.",
    dates: "September 2026 — November 2026",
    howToJoin: "Applications open August 2026. Submit a short statement of intent and a 2-minute video sample.",
    thumbnailUrl: "/images/political-education.jpg",
    resources: [
      { id: "res-1", title: "Field Recording Guide", type: "pdf", url: "#" },
      { id: "res-2", title: "Safety Protocol for Journalists", type: "pdf", url: "#" },
    ],
    relatedFilmIds: ["film-001", "film-006"],
    relatedStudioIds: [],
    enrolledCount: 124,
    completionRate: 78,
    status: "published",
    createdAt: "2026-04-10T10:00:00Z",
    updatedAt: "2026-06-15T14:30:00Z",
  },
  {
    id: "acad-2",
    title: "Visual Storytelling for Human Rights",
    slug: "visual-storytelling-human-rights",
    type: "workshop",
    format: "hybrid",
    description: "A hands-on workshop in photography and video for human rights documentation — from framing a subject to building an advocacy campaign.",
    objectives: [
      "Master composition and framing for human rights documentation",
      "Learn consent-based practices for photographing vulnerable communities",
      "Edit short-form video for social media advocacy",
      "Understand legal considerations for visual evidence",
    ],
    whoLeads: "Tanya Habjouqa",
    whoItsFor: "Human rights workers, photojournalists, NGO staff, and anyone using visual media to advocate for justice.",
    duration: "3 days (intensive)",
    isFree: true,
    price: null,
    scholarshipNote: "Free for all participants. Travel stipends available for attendees from the Global South.",
    dates: "October 18-20, 2026",
    howToJoin: "Register through the DSH website. Limited to 30 participants per cohort.",
    thumbnailUrl: "/images/journalism.jpg",
    resources: [
      { id: "res-3", title: "Visual Ethics Handbook", type: "pdf", url: "#" },
    ],
    relatedFilmIds: [],
    relatedStudioIds: [],
    enrolledCount: 56,
    completionRate: 92,
    status: "published",
    createdAt: "2026-05-01T09:00:00Z",
    updatedAt: "2026-06-20T11:00:00Z",
  },
  {
    id: "acad-3",
    title: "Community Screening Toolkit",
    slug: "community-screening-toolkit",
    type: "toolkit",
    format: "downloadable",
    description: "Everything you need to organize impactful film screenings in your community — from venue planning to post-screening facilitation guides.",
    objectives: [
      "Plan and execute community film screening events",
      "Facilitate meaningful post-screening discussions",
      "Build partnerships with local organizations and venues",
      "Measure and report screening impact",
    ],
    whoLeads: "DSH Academy Team",
    whoItsFor: "Community leaders, educators, film clubs, and anyone who wants to bring powerful documentary films to their community.",
    duration: "Self-paced",
    isFree: true,
    price: null,
    scholarshipNote: "Freely available to download and use.",
    dates: "Available now",
    howToJoin: "Download directly from the Academy page. No registration required.",
    thumbnailUrl: "/images/support.jpg",
    resources: [
      { id: "res-5", title: "Screening Planning Checklist", type: "pdf", url: "#" },
      { id: "res-6", title: "Facilitation Guide Template", type: "pdf", url: "#" },
      { id: "res-7", title: "Impact Measurement Toolkit", type: "toolkit", url: "#" },
    ],
    relatedFilmIds: ["film-001", "film-003"],
    relatedStudioIds: [],
    enrolledCount: 312,
    completionRate: 65,
    status: "published",
    createdAt: "2026-03-15T08:00:00Z",
    updatedAt: "2026-06-01T16:00:00Z",
  },
  {
    id: "acad-4",
    title: "Emerging Voices Fellowship",
    slug: "emerging-voices-fellowship",
    type: "mentorship",
    format: "hybrid",
    description: "A 6-month fellowship supporting new filmmakers from underrepresented regions — mentorship, funding, and a platform to share your first major work.",
    objectives: [
      "Develop a short documentary project from concept to completion",
      "Receive one-on-one mentorship from established filmmakers",
      "Access production funding and equipment",
      "Screen finished work through DSH distribution channels",
    ],
    whoLeads: "Kamal Aljafari",
    whoItsFor: "First-time filmmakers from the Middle East, North Africa, South Asia, and other underrepresented regions.",
    duration: "6 months",
    isFree: true,
    price: null,
    scholarshipNote: "Fully funded fellowship. Fellows receive a production grant, equipment access, and mentorship at no cost.",
    dates: "January 2027 — June 2027",
    howToJoin: "Applications open October 2026. Submit a project proposal, CV, and a short video introduction.",
    thumbnailUrl: "/images/studio.jpg",
    resources: [
      { id: "res-8", title: "Fellowship Application Guide", type: "pdf", url: "#" },
    ],
    relatedFilmIds: [],
    relatedStudioIds: [],
    enrolledCount: 18,
    completionRate: 44,
    status: "published",
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-07-05T09:00:00Z",
  },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: "art-1",
    title: "Free Fish: A Story of Resistance Under Siege",
    slug: "free-fish-story-of-resistance",
    tag: "film",
    excerpt: "A completed short documentary directed by Bisan Owda — looking at daily life under conditions designed to make life impossible.",
    date: "2026-06-20",
    body: [
      { id: "b1", type: "text", content: "Free Fish is a completed short documentary directed by Bisan Owda that stays close to the daily labour of remaining human under siege. The film follows fishermen who navigate increasingly restricted waters off the coast of Gaza, capturing how the simple act of casting a net carries both economic necessity and symbolic weight." },
      { id: "b2", type: "image", content: "/images/slider2.jpg", caption: "Still from Free Fish", credit: "DSH Productions" },
      { id: "b3", type: "quote", content: "To witness is to take responsibility for what has been seen, heard and understood." },
      { id: "b4", type: "text", content: "The film refuses the distance through which violence is made acceptable, centering the people living it rather than reducing them to statistics. Owda weaves together personal testimony, community voices, and striking visual contrasts between the beauty of the Mediterranean coast and the harshness of occupation." },
      { id: "b5", type: "heading", content: "Why This Film Matters", level: 2 },
      { id: "b6", type: "text", content: "At a moment when coverage focuses overwhelmingly on conflict events, this film insists on showing the texture of everyday existence, reminding audiences that resistance takes many forms beyond the spectacular. Free Fish enters a global conversation about the erasure of Palestinian daily life from mainstream media." },
    ],
    mainImage: "/images/slider2.jpg",
    mainImageCaption: "Free Fish — production still",
    mainImageCredit: "Don't Skip Humanity",
    author: { name: "Carolina Beltrão", avatar: "/images/infocus.jpg", bio: "Creative Director & Strategist at DSH" },
    gallery: [],
    status: "published",
    scheduledDate: null,
    seo: { metaDescription: "Free Fish — a short documentary by Bisan Owda.", socialShareImage: "" },
    createdAt: "2026-06-15T10:00:00Z",
    updatedAt: "2026-06-20T14:30:00Z",
  },
  {
    id: "art-2",
    title: "Why Ethical Storytelling Demands Accountability",
    slug: "ethical-storytelling-accountability",
    tag: "opinion",
    excerpt: "Storytelling is never neutral. The way stories are told shapes whose lives are mourned and whose humanity is denied.",
    date: "2026-06-18",
    body: [
      { id: "b1", type: "heading", content: "The Problem with Distance", level: 2 },
      { id: "b2", type: "text", content: "Most media about conflict operates from distance — geographic, emotional, and political. This distance is a choice, and it serves power. It allows audiences to consume suffering without confronting the systems that produce it, to feel informed without feeling implicated." },
      { id: "b3", type: "text", content: "Ethical storytelling means refusing that distance. It means naming structures of power, protecting the people in the story, and being accountable to them after the story is told. It means rejecting the extractive model of parachute journalism and building relationships that outlast the production cycle." },
      { id: "b4", type: "quote", content: "We don't give a voice to the voiceless — we amplify voices that have been systematically ignored, silenced, or misrepresented." },
      { id: "b5", type: "heading", content: "Accountability Beyond Publication", level: 2 },
      { id: "b6", type: "text", content: "Accountability doesn't end when the story is published. It continues in how the story circulates, who profits from it, and whether the communities depicted benefit from the attention. At DSH, we build redistribution into our model — ensuring that the communities our work comes from receive material support." },
    ],
    mainImage: "/images/journalism.jpg",
    mainImageCaption: "DSH editorial",
    mainImageCredit: "Don't Skip Humanity",
    author: { name: "Carolina Beltrão", avatar: "/images/infocus.jpg", bio: "Creative Director & Strategist at DSH" },
    gallery: [],
    status: "published",
    scheduledDate: null,
    seo: { metaDescription: "Why ethical storytelling demands accountability.", socialShareImage: "" },
    createdAt: "2026-06-10T09:00:00Z",
    updatedAt: "2026-06-18T11:00:00Z",
  },
  {
    id: "art-3",
    title: "YALLA Podcast: Conversations with Palestinian Cultural Workers",
    slug: "yalla-podcast-launch",
    tag: "interview",
    excerpt: "An interview series amplifying voices that have been systematically ignored, silenced, or misrepresented.",
    date: "2026-06-25",
    body: [
      { id: "b1", type: "text", content: "YALLA is an interview series that sits with Palestinian cultural workers, activists, and journalists — conversations that challenge the dominant frame and refuse the simplifications of mainstream media. Each episode centres a single voice, allowing space for complexity, contradiction, and nuance." },
      { id: "b2", type: "quote", content: "We don't give a voice to the voiceless — we amplify voices that have been systematically ignored." },
      { id: "b3", type: "text", content: "The series launches with three episodes featuring conversations with filmmakers, educators, and community organisers. New episodes release biweekly through the DSH Studio." },
    ],
    mainImage: "/images/political-education.jpg",
    mainImageCaption: "YALLA podcast recording",
    mainImageCredit: "DSH Studio",
    author: { name: "Tiago Zorro", avatar: "/images/studio.jpg", bio: "Project Lead at DSH" },
    gallery: [],
    status: "published",
    scheduledDate: null,
    seo: { metaDescription: "YALLA podcast — conversations with Palestinian cultural workers.", socialShareImage: "" },
    createdAt: "2026-06-22T08:00:00Z",
    updatedAt: "2026-06-25T10:00:00Z",
  },
];

export const MOCK_EVENTS: DSHEvent[] = [
  {
    id: "evt-1",
    title: "Free Fish — Community Screening & Q&A",
    slug: "free-fish-community-screening",
    tag: "screening",
    excerpt: "A community screening of Free Fish followed by a conversation with the production team.",
    description: "Join us for an intimate screening of Free Fish, a short documentary directed by Bisan Owda. The screening will be followed by a Q&A with the production team, exploring the political context behind the film and the ethics of representation in documentary filmmaking. Light refreshments will be provided. Doors open at 18:30.",
    startDate: "2026-07-20T19:00:00Z",
    endDate: "2026-07-20T21:30:00Z",
    mainImage: "/images/slider1.jpg",
    partners: [
      { id: "p1", name: "Casa Palestina", logo: "" },
      { id: "p2", name: "Cinéma du Réel", logo: "" },
    ],
    address: "Instituto Cervantes, Lisbon, Portugal",
    ticketType: "free",
    ticketUrl: "#",
    ticketPrice: null,
    status: "upcoming",
    rsvpCount: 87,
    capacity: 150,
    createdAt: "2026-06-25T10:00:00Z",
    updatedAt: "2026-07-01T14:00:00Z",
  },
  {
    id: "evt-2",
    title: "Academy Workshop: Ethical Storytelling for Journalists",
    slug: "ethical-storytelling-workshop",
    tag: "workshop",
    excerpt: "A hands-on workshop on ethical narrative, consent, and naming power in journalism.",
    description: "A free Academy workshop covering ethical storytelling frameworks — consent, context, accountability, and collaboration. Built for journalists, organisers, and filmmakers already doing the work. Practical tools, not theory alone. Participants will leave with a concrete toolkit for ethical practice.",
    startDate: "2026-07-25T10:00:00Z",
    endDate: "2026-07-25T16:00:00Z",
    mainImage: "/images/political-education.jpg",
    partners: [
      { id: "p3", name: "Slow Factory", logo: "" },
    ],
    address: "Online — Zoom",
    ticketType: "free",
    ticketUrl: "#",
    ticketPrice: null,
    status: "upcoming",
    rsvpCount: 234,
    capacity: 300,
    createdAt: "2026-06-20T09:00:00Z",
    updatedAt: "2026-07-02T11:00:00Z",
  },
  {
    id: "evt-4",
    title: "Palestine Film Night — Porto",
    slug: "palestine-film-night-porto",
    tag: "screening",
    excerpt: "An evening of Palestinian cinema curated by DSH — three short films followed by a panel discussion.",
    description: "Three short Palestinian films curated by Don't Skip Humanity, followed by a panel discussion on cinema, witness, and collective memory. Part of the ongoing DSH public programming series. All proceeds support DSH's redistribution fund.",
    startDate: "2026-08-05T20:00:00Z",
    endDate: "2026-08-05T23:00:00Z",
    mainImage: "/images/studio.jpg",
    partners: [
      { id: "p4", name: "Casa Palestina", logo: "" },
      { id: "p5", name: "Porto Film Commission", logo: "" },
    ],
    address: "Rivoli Teatro Municipal, Porto, Portugal",
    ticketType: "paid",
    ticketUrl: "#",
    ticketPrice: 8,
    status: "upcoming",
    rsvpCount: 45,
    capacity: 200,
    createdAt: "2026-07-01T10:00:00Z",
    updatedAt: "2026-07-05T12:00:00Z",
  },
];

/* ─── Helpers ─────────────────────────────────────────────────── */

export function getFilmBySlug(slug: string): Film | undefined {
  return MOCK_FILMS.find((f) => f.slug === slug);
}

export function getProgramBySlug(slug: string): AcademyProgram | undefined {
  return MOCK_PROGRAMS.find((p) => p.slug === slug);
}

export function getArticleBySlug(slug: string): Article | undefined {
  return MOCK_ARTICLES.find((a) => a.slug === slug);
}

export function getEventBySlug(slug: string): DSHEvent | undefined {
  return MOCK_EVENTS.find((e) => e.slug === slug);
}
